spring:
  application:
    name: fdn-authorize
  datasource:
    username: root
    password: l
    url: 112.74.35.178
    data-password:
server:
  port: 9001
global:
  config:
    jwt:
      pub-key-path: D:\\11\\publicKey  #公钥文件路径
      pri-key-path: D:\\11\\privateKey #私钥文件路径
      secret: 8102744011034
      token-expire: 120
      cookie-name: TOKEN
      cookie-max-age: 1800
      unit: minutes