logging:
  config: classpath:logback.xml
spring:
  application:
    name: basic-authorize
  datasource:
    username:
    password:
    url:
    data-password:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true # 404时抛出异常
  resources:
    add-mappings: false # 禁止为工程资源文件添加映射
server:
  port: 9001
  servlet:
    session:
      cookie:
        http-only: true  #禁止js脚本读取cookie信息
global:
  config:
    core:
      task:
        pool:
          enable: false    #是否启用自定义线程池子
          corePoolSize: 20   #核心线程数
          maxPoolSize: 40    #最大线程数
          keepAliveSeconds: 300   #线程存活时间
          queueCapacity: 50      #队列容量
    auth:
      token:
        token-model: jwt  #使用的令牌模型
        jwt:
          pub-key-path: D:\\11\\publicKey  #公钥文件路径
          pri-key-path: D:\\11\\privateKey #私钥文件路径
          secret:            #生成密钥对的密码
